kind: Job
apiVersion: batch/v1
metadata:
  name: nginx-job
  namespace: nginx
spec:
  completions: 1 # no of times completions to run job
  parallelism: 1 # no of pods to run job in parallel

  template:
    metadata:
      name: nginx-job-pod
      labels: 
        app: batch-task
    spec:
      containers:
      - name: batch-container
        image: busybox:latest
        command: ["sh", "-c", "echo Hello This is onetime JOB && sleep 10" ]
      restartPolicy: Never # once job done it terminate
